lista = []
num1 = float(input('Digite um número real: '))
lista.append(num1)
num2 = float(input('Digite um número real: '))
lista.append(num2)
num3 = float(input('Digite um número real: '))
lista.append(num3)
num4 = float(input('Digite um número real: '))
lista.append(num4)
num5 = float(input('Digite um número real: '))
lista.append(num5)
num6 = float(input('Digite um número real: '))
lista.append(num6)
num7 = float(input('Digite um número real: '))
lista.append(num7)
num8 = float(input('Digite um número real: '))
lista.append(num8)
num9 = float(input('Digite um número real: '))
lista.append(num9)
num10 = float(input('Digite um número real: '))
lista.append(num10)
lista.reverse()
print(lista)
