lista_notas = []
nota1 = float(input('Digite uma nota: '))
lista_notas.append(nota1)
nota2 = float(input('Digite uma nota: '))
lista_notas.append(nota2)
nota3 = float(input('Digite uma nota: '))
lista_notas.append(nota3)
nota4 = float(input('Digite uma nota: '))
lista_notas.append(nota4)
print(lista_notas)
lista_notas.remove(nota1)
lista_notas.remove(nota3)
print(lista_notas)
